config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/result'
  post 'static_pages/result', as: 'result'
  get 'static_pages/home', as: 'home'
  root 'static_pages#home'
end

app/models/application_form.rb
class ApplicationForm
  include ActiveModel::Model

  attr_accessor :height, :weight, :old#, :gender, :activity, :purpose
  
  validates :height, :weight, :old, numericality: { only_integer: true, greater_than: 0, less_than: 500 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "!!!hello,world!!!"
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @applicationForm = ApplicationForm.new
    # フォーム入力値がエラーの際にエラー文を表示しようとした。
    # その際、errorsがnil、未定義のメソッドであるというエラー。
    # # homeアクションでもresultアクションのように、ApplicationForm.newによる初期化が必要。
    # https://stackoverflow.com/questions/18136632/undefined-method-errors-for-nilnilclass-when-calling-on-errors-method
  end
  
  def result
    # @msg ="hellooooooo"
    @applicationForm = ApplicationForm.new(applicationForm_params)
    unless @applicationForm.valid? then render 'home' end
  end
  
  private
    
    def applicationForm_params
      params.permit(:height, :weight, :old)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/index.html.erb
<!-- component template -->
<script type="text/x-template" id="grid-template">
  <table>
    <thead>
    <tr>
      <th v-for="key in columns"
          @click="sortBy(key)"
          :class="{ active: sortKey == key }">
        {{ key | capitalize }}
        <span class="arrow" :class="sortOrders[key] > 0 ? 'asc' : 'dsc'">
          </span>
      </th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="entry in filteredData">
      <td v-for="key in columns">
        {{entry[key]}}
      </td>
    </tr>
    </tbody>
  </table>
</script>

<!-- demo root element -->
<div id="demo">
  <form id="search">
    Search <input name="query" v-model="searchQuery">
  </form>
  <demo-grid
  :data="gridData"
  :columns="gridColumns"
  :filter-key="searchQuery">
  </demo-grid>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MacroApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'hello_vue' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @applicationForm.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @applicationForm.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<%= form_with url: static_pages_result_url, local: true do |form| %>
  <%= render 'shared/error_messages' %>
  
  <%= form.select :gender, { "男": "male", "女": "female" }, {prompt: "性別を選択"}, { class: "selectbox" } %>
  <br><br>
  <%= form.telephone_field :height, placeholder: "身長を入力", class: 'form-control' %>
  <br><br>
  <%= form.telephone_field :weight, placeholder: "体重を入力", class: 'form-control' %>
  <br><br>
  <%= form.telephone_field :old, placeholder: "年齢を入力", class: 'form-control' %>
  <br><br>
  <%= form.select :activity, { "低い": "low", "まあまあ": "mid", "高い": "high" }, {prompt: "アクティブ度を選択"}, { class: "selectbox" } %>
  <br><br>
  <%= form.select :purpose, { "減量": "loss", "維持": "maintenance", "増量": "increase" }, {prompt: "目的を選択"}, { class: "selectbox" } %>
  <br><br>
  <%= form.submit "計算する", class: 'result-button'  %>
<% end %>

app/views/static_pages/result.html.erb
<div class="result-page">
<!--基礎代謝を求める（男、女）-->
<% basal_metabolism = 0 %>
<% case params[:gender] %>
<% when "male" %>
  <% basal_metabolism = (10 * params[:weight].to_i + 6.25 * params[:height].to_i - 5 * params[:old].to_i + 5).round(0) %>
<% when "female" %>
  <% basal_metabolism = (10 * params[:weight].to_i + 6.25 * params[:height].to_i - 5 * params[:old].to_i - 161).round(0) %>
<% end %>
<p>基礎代謝</p>
<%= basal_metabolism %> kcal

<!--活動量（少ない、普通、多い）-->
<% active_volume = 0 %>
<% case params[:activity] %>
<% when "low" %>
  <% active_volume = 1.2 %>
<% when "mid" %>
  <% active_volume = 1.55 %>
<% when "high" %>
  <% active_volume = 1.725 %>
<% end %>

<!--目標体重（減量、維持、増量）-->
<% purpose = 0 %>
<% case params[:purpose] %>
<% when "loss" %>
  <% purpose = 0.8 %>
<% when "maintenance" %>
  <% purpose = 1 %>
<% when "increase" %>
  <% purpose = 1.2 %>
<% end %>

<p>総摂取カロリー</p>
<% total_calorie = (basal_metabolism * active_volume * purpose).round(0) %>
<%= total_calorie %> kcal

<p>たんぱく質</p>
<% protein = (params[:weight].to_i * 2 * 4).round(0) %>
<%= protein / 4 %> g

<p>脂質</p>
<% liqid = (total_calorie / 4).round(0) %>
<%= liqid / 9 %> g

<p>炭水化物</p>
<% carbohydrate = (total_calorie - protein - liqid).round(0) %>
<%= carbohydrate / 4 %> g
<!--<%= @msg %>-->
</div>